Fix(angular.json): Disable SSG and SSR
There is an error that occurs because of SSG and SSR: ERROR TypeError: this.document.head.prepend is not a function

For dev purpose SSG and SSR are disabled.